import { erc20Abi } from 'viem';
import {
  AccountingAbi,
  CSModuleAbi,
  CuratedGateAbi,
  CuratedModuleAbi,
  EjectorAbi,
  ExitPenaltiesAbi,
  FeeDistributorAbi,
  FeeOracleAbi,
  HashConsensusAbi,
  OperatorsDataAbi,
  ParametersRegistryAbi,
  PermissionlessGateAbi,
  SMDiscoveryAbi,
  StakingRouterAbi,
  ValidatorsExitBusOracleAbi,
  ValidatorStrikesAbi,
  VerifierAbi,
  VettedGateAbi,
  WithdrawalVaultAbi,
} from '../../abi/index.js';
import { CONTRACT_NAMES } from './contract-names.js';

export const CONTRACT_BASE_ABI = {
  [CONTRACT_NAMES.stakingRouter]: StakingRouterAbi,
  [CONTRACT_NAMES.validatorsExitBusOracle]: ValidatorsExitBusOracleAbi,
  [CONTRACT_NAMES.withdrawalVault]: WithdrawalVaultAbi,
  [CONTRACT_NAMES.stETH]: erc20Abi,
  [CONTRACT_NAMES.wstETH]: erc20Abi,
  [CONTRACT_NAMES.SMDiscovery]: SMDiscoveryAbi,
  [CONTRACT_NAMES.csModule]: CSModuleAbi,
  [CONTRACT_NAMES.curatedModule]: CuratedModuleAbi,
  [CONTRACT_NAMES.accounting]: AccountingAbi,
  [CONTRACT_NAMES.ejector]: EjectorAbi,
  [CONTRACT_NAMES.exitPenalties]: ExitPenaltiesAbi,
  [CONTRACT_NAMES.feeDistributor]: FeeDistributorAbi,
  [CONTRACT_NAMES.feeOracle]: FeeOracleAbi,
  [CONTRACT_NAMES.hashConsensus]: HashConsensusAbi,
  [CONTRACT_NAMES.parametersRegistry]: ParametersRegistryAbi,
  [CONTRACT_NAMES.validatorStrikes]: ValidatorStrikesAbi,
  [CONTRACT_NAMES.verifier]: VerifierAbi,
  [CONTRACT_NAMES.operatorsData]: OperatorsDataAbi,
  [CONTRACT_NAMES.permissionlessGate]: PermissionlessGateAbi,
  [CONTRACT_NAMES.vettedGate]: VettedGateAbi,
  [CONTRACT_NAMES.curatedGate1]: CuratedGateAbi,
} as const;
