export const PUBKEY_LENGTH_BYTES = 48;
export const SIGNATURE_LENGTH_BYTES = 96;

export const EJECTABLE_EPOCH_COUNT = 256n;

export enum KEY_STATUS {
  NON_QUEUED = 'NON_QUEUED',
  DEPOSITABLE = 'DEPOSITABLE',
  ACTIVATION_PENDING = 'ACTIVATION_PENDING',
  ACTIVE = 'ACTIVE',
  EXITING = 'EXITING',
  WITHDRAWAL_PENDING = 'WITHDRAWAL_PENDING',
  WITHDRAWN = 'WITHDRAWN',

  UNCHECKED = 'UNCHECKED',
  DUPLICATED = 'DUPLICATED',
  INVALID = 'INVALID',

  UNBONDED = 'UNBONDED',
  EXIT_REQUESTED = 'EXIT_REQUESTED',
  SLASHED = 'SLASHED',

  EJECTABLE = 'EJECTABLE',
  WITH_STRIKES = 'WITH_STRIKES',
}
