export enum OPERATOR_TYPE {
  CSM_DEF = 'CSM_DEF',
  CSM_LEA = 'CSM_LEA',
  CSM_ICS = 'CSM_ICS',
  CM_PO = 'CM_PO',
  CM_PTO = 'CM_PTO',
  CM_PGO = 'CM_PGO',
  CM_DO = 'CM_DO',
  CM_EEO = 'CM_EEO',
  CM_MODC = 'CM_MODC',
  CM_IODC = 'CM_IODC',
  CSM0x02_DEF = 'CSM0x02_DEF',
  CC = 'CC',
}

export const OPERATOR_CURVE_ID = {
  [OPERATOR_TYPE.CSM_DEF]: 0n,
  [OPERATOR_TYPE.CSM_LEA]: 1n,
  [OPERATOR_TYPE.CSM_ICS]: 2n,
  [OPERATOR_TYPE.CM_PTO]: 1n,
  [OPERATOR_TYPE.CM_PO]: 2n,
  [OPERATOR_TYPE.CM_PGO]: 3n,
  [OPERATOR_TYPE.CM_DO]: 4n,
  [OPERATOR_TYPE.CM_EEO]: 5n,
  [OPERATOR_TYPE.CM_MODC]: 6n,
  [OPERATOR_TYPE.CM_IODC]: 7n,
  [OPERATOR_TYPE.CSM0x02_DEF]: 0n,
  [OPERATOR_TYPE.CC]: undefined,
} as const;
