export const CuratedModuleAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'moduleType', type: 'bytes32', internalType: 'bytes32' },
      { name: 'lidoLocator', type: 'address', internalType: 'address' },
      { name: 'parametersRegistry', type: 'address', internalType: 'address' },
      { name: 'accounting', type: 'address', internalType: 'address' },
      { name: 'exitPenalties', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'ACCOUNTING',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IAccounting' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'EXIT_PENALTIES',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IExitPenalties' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'FEE_DISTRIBUTOR',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'LIDO_LOCATOR',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract ILidoLocator' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'OPERATOR_ADDRESSES_ADMIN_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PARAMETERS_REGISTRY',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IParametersRegistry' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PAUSE_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'RESUME_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'STETH',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IStETH' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'addValidatorKeysETH',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'keysCount', type: 'uint256', internalType: 'uint256' },
      { name: 'publicKeys', type: 'bytes', internalType: 'bytes' },
      { name: 'signatures', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'addValidatorKeysStETH',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'keysCount', type: 'uint256', internalType: 'uint256' },
      { name: 'publicKeys', type: 'bytes', internalType: 'bytes' },
      { name: 'signatures', type: 'bytes', internalType: 'bytes' },
      {
        name: 'permit',
        type: 'tuple',
        internalType: 'struct IAccounting.PermitInput',
        components: [
          { name: 'value', type: 'uint256', internalType: 'uint256' },
          { name: 'deadline', type: 'uint256', internalType: 'uint256' },
          { name: 'v', type: 'uint8', internalType: 'uint8' },
          { name: 'r', type: 'bytes32', internalType: 'bytes32' },
          { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addValidatorKeysWstETH',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'keysCount', type: 'uint256', internalType: 'uint256' },
      { name: 'publicKeys', type: 'bytes', internalType: 'bytes' },
      { name: 'signatures', type: 'bytes', internalType: 'bytes' },
      {
        name: 'permit',
        type: 'tuple',
        internalType: 'struct IAccounting.PermitInput',
        components: [
          { name: 'value', type: 'uint256', internalType: 'uint256' },
          { name: 'deadline', type: 'uint256', internalType: 'uint256' },
          { name: 'v', type: 'uint8', internalType: 'uint8' },
          { name: 'r', type: 'bytes32', internalType: 'bytes32' },
          { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'changeNodeOperatorAddresses',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'newManagerAddress', type: 'address', internalType: 'address' },
      { name: 'newRewardAddress', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'changeNodeOperatorRewardAddress',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'newAddress', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'confirmNodeOperatorManagerAddressChange',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'confirmNodeOperatorRewardAddressChange',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createNodeOperator',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      {
        name: 'managementProperties',
        type: 'tuple',
        internalType: 'struct NodeOperatorManagementProperties',
        components: [
          { name: 'managerAddress', type: 'address', internalType: 'address' },
          { name: 'rewardAddress', type: 'address', internalType: 'address' },
          { name: 'extendedManagerPermissions', type: 'bool', internalType: 'bool' },
        ],
      },
      { name: 'referrer', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getActiveNodeOperatorsCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperator',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct NodeOperator',
        components: [
          { name: 'totalAddedKeys', type: 'uint32', internalType: 'uint32' },
          { name: 'totalWithdrawnKeys', type: 'uint32', internalType: 'uint32' },
          { name: 'totalDepositedKeys', type: 'uint32', internalType: 'uint32' },
          { name: 'totalVettedKeys', type: 'uint32', internalType: 'uint32' },
          { name: 'stuckValidatorsCount', type: 'uint32', internalType: 'uint32' },
          { name: 'depositableValidatorsCount', type: 'uint32', internalType: 'uint32' },
          { name: 'targetLimit', type: 'uint32', internalType: 'uint32' },
          { name: 'targetLimitMode', type: 'uint8', internalType: 'uint8' },
          { name: 'totalExitedKeys', type: 'uint32', internalType: 'uint32' },
          { name: 'enqueuedCount', type: 'uint32', internalType: 'uint32' },
          { name: 'managerAddress', type: 'address', internalType: 'address' },
          { name: 'proposedManagerAddress', type: 'address', internalType: 'address' },
          { name: 'rewardAddress', type: 'address', internalType: 'address' },
          { name: 'proposedRewardAddress', type: 'address', internalType: 'address' },
          { name: 'extendedManagerPermissions', type: 'bool', internalType: 'bool' },
          { name: 'usedPriorityQueue', type: 'bool', internalType: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorIds',
    inputs: [
      { name: 'offset', type: 'uint256', internalType: 'uint256' },
      { name: 'limit', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'nodeOperatorIds', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorIsActive',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorManagementProperties',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct NodeOperatorManagementProperties',
        components: [
          { name: 'managerAddress', type: 'address', internalType: 'address' },
          { name: 'rewardAddress', type: 'address', internalType: 'address' },
          { name: 'extendedManagerPermissions', type: 'bool', internalType: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorNonWithdrawnKeys',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorOwner',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorSummary',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'targetLimitMode', type: 'uint256', internalType: 'uint256' },
      { name: 'targetValidatorsCount', type: 'uint256', internalType: 'uint256' },
      { name: 'stuckValidatorsCount', type: 'uint256', internalType: 'uint256' },
      { name: 'refundedValidatorsCount', type: 'uint256', internalType: 'uint256' },
      { name: 'stuckPenaltyEndTimestamp', type: 'uint256', internalType: 'uint256' },
      { name: 'totalExitedValidators', type: 'uint256', internalType: 'uint256' },
      { name: 'totalDepositedValidators', type: 'uint256', internalType: 'uint256' },
      { name: 'depositableValidatorsCount', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorTotalDepositedKeys',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'totalDepositedKeys', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNodeOperatorsCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSigningKeys',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'startIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'keysCount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bytes', internalType: 'bytes' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSigningKeysWithSignatures',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'startIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'keysCount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'keys', type: 'bytes', internalType: 'bytes' },
      { name: 'signatures', type: 'bytes', internalType: 'bytes' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStakingModuleSummary',
    inputs: [],
    outputs: [
      { name: 'totalExitedValidators', type: 'uint256', internalType: 'uint256' },
      { name: 'totalDepositedValidators', type: 'uint256', internalType: 'uint256' },
      { name: 'depositableValidatorsCount', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getType',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isPaused',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposeNodeOperatorManagerAddressChange',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'proposedAddress', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'proposeNodeOperatorRewardAddressChange',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'proposedAddress', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeKeys',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' },
      { name: 'startIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'keysCount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resetNodeOperatorManagerAddress',
    inputs: [{ name: 'nodeOperatorId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'NodeOperatorAdded',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'managerAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'rewardAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'extendedManagerPermissions', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NodeOperatorManagerAddressChanged',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'oldAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newAddress', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NodeOperatorRewardAddressChanged',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'oldAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newAddress', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SigningKeyAdded',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'pubkey', type: 'bytes', indexed: false, internalType: 'bytes' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SigningKeyRemoved',
    inputs: [
      { name: 'nodeOperatorId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'pubkey', type: 'bytes', indexed: false, internalType: 'bytes' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'NotImplemented', inputs: [] },
  { type: 'error', name: 'NodeOperatorDoesNotExist', inputs: [] },
] as const;
